const MODULES=[
['dashboard','📊','Dashboard','Resumen general de la actividad'],['clientes','👥','Clientes','Base de datos de clientes'],['productos','🍰','Productos','Catálogo y precios de venta'],['presupuestos','🧾','Presupuestos','Documentos comerciales'],['facturacion','💶','Facturación','Control de facturas y cobros'],['catering','🍽️','Catering','Calendario de eventos'],['produccion','🏭','Producción','Pedidos aceptados y tareas'],['dietario','📖','Dietario anual','Planificación diaria'],['ingredientes','🥣','Ingredientes','Materias primas y costes'],['escandallos','📐','Escandallos','Costes y márgenes'],['proveedores','🚚','Proveedores','Directorio de proveedores'],['catalogo','📦','Catálogo proveedores','Tarifas de compra'],['comparador','📈','Comparador','Comparativa de precios'],['compras','🛒','Compras','Pedidos de compra'],['menaje','🍽️','Menaje','Inventario y reservas'],['bebidas','🥤','Bebidas','Stock y consumos'],['visitadores','🩺','Visitadores médicos','Contactos y presupuestos'],['fichas','📄','Fichas técnicas','Documentación de producto'],['documentos','🖨️','Motor de documentos','Impresión y exportación']];
const SCHEMAS={
clientes:[['nombre','Nombre','text'],['empresa','Empresa','text'],['telefono','Teléfono','tel'],['email','Email','email'],['nif','NIF/CIF','text'],['direccion','Dirección','textarea']],
productos:[['nombre','Producto','text'],['referencia','Referencia','text'],['categoria','Categoría','text'],['unidad','Unidad','select','unidad,kg,g,litro,ud'],['coste','Coste (€)','number'],['precio','Precio venta (€)','number'],['iva','IVA (%)','number']],
presupuestos:[['cliente','Cliente','text'],['fecha','Fecha','date'],['descripcion','Descripción','textarea'],['total','Total (€)','number'],['estado','Estado','select','Borrador,Enviado,Aceptado,Rechazado']],
facturacion:[['cliente','Cliente','text'],['numero','Número factura','text'],['fecha','Fecha','date'],['base','Base (€)','number'],['iva','IVA (%)','number'],['estado','Estado','select','Pendiente,Cobrada,Vencida']],
catering:[['cliente','Cliente','text'],['fecha','Fecha','date'],['hora','Hora','time'],['lugar','Lugar','text'],['personas','Personas','number'],['estado','Estado','select','Pendiente,Aceptado,Realizado,Cancelado']],
produccion:[['pedido','Pedido / catering','text'],['cliente','Cliente','text'],['fecha','Fecha producción','date'],['responsable','Responsable','text'],['estado','Estado','select','Pendiente,En curso,Terminado']],
dietario:[['fecha','Fecha','date'],['producto','Producto / tarea','text'],['unidades','Unidades','number'],['notas','Notas','textarea']],
ingredientes:[['nombre','Ingrediente','text'],['proveedor','Proveedor','text'],['formato','Formato','text'],['precio','Precio formato (€)','number'],['unidad','Unidad base','text'],['stock','Stock','number']],
escandallos:[['producto','Producto','text'],['costeIngredientes','Ingredientes (€)','number'],['manoObra','Mano de obra (€)','number'],['packaging','Packaging (€)','number'],['precioVenta','Precio venta (€)','number']],
proveedores:[['nombre','Proveedor','text'],['contacto','Contacto','text'],['telefono','Teléfono','tel'],['email','Email','email'],['categoria','Categoría','text'],['activo','Estado','select','Activo,Inactivo']],
catalogo:[['proveedor','Proveedor','text'],['producto','Producto','text'],['formato','Formato','text'],['precio','Precio sin IVA (€)','number'],['iva','IVA (%)','number'],['fecha','Fecha precio','date']],
compras:[['proveedor','Proveedor','text'],['fecha','Fecha','date'],['descripcion','Descripción','textarea'],['total','Total (€)','number'],['estado','Estado','select','Preparando,Pedido,Recibido']],
menaje:[['articulo','Artículo','text'],['stock','Stock total','number'],['reservado','Reservado','number'],['ubicacion','Ubicación','text']],
bebidas:[['producto','Bebida','text'],['stock','Stock','number'],['unidad','Unidad','text'],['coste','Coste (€)','number'],['precio','Precio venta (€)','number']],
visitadores:[['nombre','Nombre','text'],['empresa','Empresa / laboratorio','text'],['telefono','Teléfono','tel'],['email','Email','email'],['observaciones','Observaciones','textarea']],
fichas:[['producto','Producto','text'],['alergenos','Alérgenos','textarea'],['conservacion','Conservación','textarea'],['caducidad','Caducidad','text'],['notas','Notas','textarea']]
};
const state={page:'dashboard',deferredPrompt:null,editing:null};
const $=s=>document.querySelector(s); const storeKey='cusachsHubDataV11';
const data=JSON.parse(localStorage.getItem(storeKey)||'{}');
function save(){localStorage.setItem(storeKey,JSON.stringify(data))}
function arr(k){return data[k]||(data[k]=[])}
function money(v){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v||0))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function init(){
 $('#today').textContent=new Intl.DateTimeFormat('es-ES',{dateStyle:'medium'}).format(new Date());
 $('#nav').innerHTML=MODULES.map(([id,ic,n])=>`<button class="nav-btn" data-page="${id}"><span>${ic}</span>${n}</button>`).join('');
 $('#nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)openPage(b.dataset.page)};
 $('#loginForm').onsubmit=e=>{e.preventDefault();if($('#user').value==='admin'&&$('#pass').value==='cusachs'){sessionStorage.setItem('cusachsLogin','1');showApp()}else alert('Usuario o contraseña incorrectos')};
 $('#logoutBtn').onclick=()=>{sessionStorage.removeItem('cusachsLogin');location.reload()};
 $('#menuBtn').onclick=()=>$('#sidebar').classList.add('open'); $('#closeMenu').onclick=()=>$('#sidebar').classList.remove('open');
 $('#backupBtn').onclick=backup;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
 $('#installBtn').onclick=async()=>{if(state.deferredPrompt){state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
 if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
 if(sessionStorage.getItem('cusachsLogin'))showApp();
}
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');openPage('dashboard')}
function openPage(id){state.page=id;$('#sidebar').classList.remove('open');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const m=MODULES.find(x=>x[0]===id);$('#pageTitle').textContent=m[2];$('#pageSubtitle').textContent=m[3];render()}
function render(){if(state.page==='dashboard')return renderDashboard();if(state.page==='comparador')return renderComparador();if(state.page==='documentos')return renderDocumentos();renderCrud(state.page)}
function renderDashboard(){
 const pendientes=arr('presupuestos').filter(x=>x.estado!=='Aceptado').length; const facturado=arr('facturacion').reduce((s,x)=>s+Number(x.base||0)*(1+Number(x.iva||0)/100),0); const proximos=arr('catering').filter(x=>x.fecha>=new Date().toISOString().slice(0,10)).length;
 $('#content').innerHTML=`<div class="grid cards"><div class="card kpi"><span>Clientes</span><strong>${arr('clientes').length}</strong><small>registrados</small></div><div class="card kpi"><span>Presupuestos pendientes</span><strong>${pendientes}</strong><small>por revisar</small></div><div class="card kpi"><span>Facturación</span><strong>${money(facturado)}</strong><small>acumulada</small></div><div class="card kpi"><span>Próximos caterings</span><strong>${proximos}</strong><small>programados</small></div></div><div class="section-title"><h2>Accesos rápidos</h2></div><div class="grid quick-grid">${[['clientes','👥','Nuevo cliente'],['presupuestos','🧾','Nuevo presupuesto'],['catering','🍽️','Nuevo catering'],['productos','🍰','Nuevo producto'],['compras','🛒','Nueva compra'],['produccion','🏭','Producción']].map(([p,i,t])=>`<button class="card quick" data-quick="${p}"><b>${i}</b><span>${t}<small>Abrir módulo</small></span></button>`).join('')}</div><div class="section-title"><h2>Actividad reciente</h2></div><div class="card">${recentActivity()}</div>`;
 document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>openPage(b.dataset.quick));
}
function recentActivity(){const rows=[];for(const k of Object.keys(SCHEMAS)){for(const x of arr(k).slice(-2))rows.push({k,x})}return rows.length?rows.slice(-8).reverse().map(r=>`<p><span class="pill">${esc(MODULES.find(m=>m[0]===r.k)?.[2]||r.k)}</span> ${esc(Object.values(r.x).find(v=>v)||'Registro')}</p>`).join(''):'Aún no hay actividad. Empieza creando un cliente, producto o catering.'}
function renderCrud(key){const schema=SCHEMAS[key]||[['nombre','Nombre','text'],['descripcion','Descripción','textarea']];const rows=arr(key);$('#content').innerHTML=`<div class="section-title"><h2>${rows.length} registros</h2><div><button id="exportBtn" class="secondary">Exportar CSV</button> <button id="newBtn">+ Nuevo</button></div></div><div class="table-wrap">${rows.length?tableHtml(key,schema,rows):'<div class="empty">No hay registros todavía.<br><br><button id="emptyNew">Crear el primero</button></div>'}</div>`;$('#newBtn')?.addEventListener('click',()=>openModal(key));$('#emptyNew')?.addEventListener('click',()=>openModal(key));$('#exportBtn').onclick=()=>exportCsv(key);document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(key,Number(b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este registro?')){rows.splice(Number(b.dataset.del),1);save();render()}})}
function tableHtml(key,schema,rows){const cols=schema.slice(0,5);return `<table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${cols.map(c=>`<td>${formatCell(c[0],r[c[0]])}</td>`).join('')}<td class="actions"><button class="secondary" data-edit="${i}">Editar</button><button class="danger" data-del="${i}">Eliminar</button></td></tr>`).join('')}</tbody></table>`}
function formatCell(k,v){if(v==null||v==='')return '—';if(['coste','precio','total','base','precioVenta','costeIngredientes','manoObra','packaging'].includes(k))return money(v);if(k==='estado')return `<span class="pill ${['Aceptado','Cobrada','Realizado','Terminado','Recibido','Activo'].includes(v)?'ok':['Pendiente','Enviado','En curso','Preparando'].includes(v)?'warn':''}">${esc(v)}</span>`;return esc(v)}
function openModal(key,index=null){state.editing={key,index};const schema=SCHEMAS[key];const item=index==null?{}:arr(key)[index];$('#modalTitle').textContent=index==null?'Nuevo registro':'Editar registro';$('#modalFields').innerHTML=schema.map(([name,label,type,opts])=>{const val=item[name]??'';const full=type==='textarea'?' full':'';if(type==='select')return `<label class="${full}">${label}<select name="${name}"><option value="">Selecciona</option>${opts.split(',').map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></label>`;if(type==='textarea')return `<label class="${full}">${label}<textarea name="${name}">${esc(val)}</textarea></label>`;return `<label class="${full}">${label}<input name="${name}" type="${type}" value="${esc(val)}" ${type==='number'?'step="0.01"':''}></label>`}).join('');$('#modal').showModal()}
$('#modalForm')?.addEventListener('submit',e=>{});
document.addEventListener('DOMContentLoaded',()=>{init();$('#saveModal').addEventListener('click',e=>{e.preventDefault();const {key,index}=state.editing;const obj=Object.fromEntries(new FormData($('#modalForm')).entries());if(index==null)arr(key).push(obj);else arr(key)[index]=obj;save();$('#modal').close();render()})});
function exportCsv(key){const rows=arr(key);if(!rows.length)return alert('No hay datos para exportar');const headers=[...new Set(rows.flatMap(Object.keys))];const csv=[headers.join(';'),...rows.map(r=>headers.map(h=>`"${String(r[h]??'').replaceAll('"','""')}"`).join(';'))].join('\n');download(`${key}.csv`,new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}))}
function backup(){download(`cusachs-hub-backup-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify(data,null,2)],{type:'application/json'}))}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderComparador(){const rows=arr('catalogo');const grouped={};rows.forEach(r=>(grouped[(r.producto||'').toLowerCase()]??=[]).push(r));const comps=Object.values(grouped).filter(g=>g.length>1);$('#content').innerHTML=`<div class="section-title"><h2>Productos comparables</h2></div><div class="grid">${comps.length?comps.map(g=>`<div class="card"><h3>${esc(g[0].producto)}</h3>${g.sort((a,b)=>Number(a.precio)-Number(b.precio)).map((x,i)=>`<p><span class="pill ${i===0?'ok':''}">${esc(x.proveedor)}</span> ${money(x.precio)} ${i===0?'· Mejor precio':''}</p>`).join('')}</div>`).join(''):'<div class="card empty">Añade el mismo producto de dos proveedores distintos en “Catálogo proveedores” para compararlos.</div>'}</div>`}
function renderDocumentos(){$('#content').innerHTML=`<div class="grid quick-grid"><div class="card"><h2>Presupuestos</h2><p>Imprime o guarda como PDF desde el navegador.</p><button onclick="window.print()">Imprimir vista actual</button></div><div class="card"><h2>Exportaciones</h2><p>Todos los módulos permiten descargar datos en CSV.</p><button class="secondary" onclick="openPage('presupuestos')">Abrir presupuestos</button></div><div class="card"><h2>Copia de seguridad</h2><p>Descarga todos los datos guardados en esta tablet.</p><button class="secondary" onclick="backup()">Descargar JSON</button></div></div>`}
