-- Ejecuta este archivo en Supabase > SQL Editor.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['clientes','productos','ingredientes','presupuestos','catering','produccion','dietario_anual','menaje','bebidas','escandallos','proveedores','catalogo_proveedores','compras','visitadores_medicos','fichas_tecnicas','facturas'] loop
    execute format('create table if not exists public.%I (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), updated_at timestamptz default now())', t);
  end loop;
end $$;

-- Columnas básicas. Se añaden únicamente si no existen.
alter table clientes add column if not exists nombre text; alter table clientes add column if not exists contacto text; alter table clientes add column if not exists telefono text; alter table clientes add column if not exists email text; alter table clientes add column if not exists cif text; alter table clientes add column if not exists direccion text; alter table clientes add column if not exists poblacion text; alter table clientes add column if not exists codigo_postal text; alter table clientes add column if not exists observaciones text; alter table clientes add column if not exists activo boolean default true;
alter table productos add column if not exists nombre text; alter table productos add column if not exists referencia text; alter table productos add column if not exists categoria text; alter table productos add column if not exists unidad text; alter table productos add column if not exists coste numeric; alter table productos add column if not exists precio_venta numeric; alter table productos add column if not exists iva numeric default 10; alter table productos add column if not exists observaciones text; alter table productos add column if not exists activo boolean default true;

-- Para avanzar rápido, el resto de tablas usan una columna flexible JSON además de campos comunes.
do $$ declare t text; begin foreach t in array array['ingredientes','presupuestos','catering','produccion','dietario_anual','menaje','bebidas','escandallos','proveedores','catalogo_proveedores','compras','visitadores_medicos','fichas_tecnicas','facturas'] loop execute format('alter table public.%I add column if not exists datos jsonb default ''{}''::jsonb',t); end loop; end $$;

-- Política simple para una instalación interna. Revisa seguridad antes de publicar.
do $$ declare t text; begin foreach t in array array['clientes','productos','ingredientes','presupuestos','catering','produccion','dietario_anual','menaje','bebidas','escandallos','proveedores','catalogo_proveedores','compras','visitadores_medicos','fichas_tecnicas','facturas'] loop execute format('alter table public.%I enable row level security',t); begin execute format('create policy "acceso anon temporal" on public.%I for all to anon using (true) with check (true)',t); exception when duplicate_object then null; end; end loop; end $$;


-- Columnas funcionales del resto de módulos
alter table ingredientes add column if not exists nombre text; alter table ingredientes add column if not exists categoria text; alter table ingredientes add column if not exists proveedor text; alter table ingredientes add column if not exists formato text; alter table ingredientes add column if not exists cantidad_formato numeric; alter table ingredientes add column if not exists unidad text; alter table ingredientes add column if not exists precio_formato numeric; alter table ingredientes add column if not exists precio_unitario numeric; alter table ingredientes add column if not exists alergenos text; alter table ingredientes add column if not exists activo boolean default true;
alter table presupuestos add column if not exists numero text; alter table presupuestos add column if not exists cliente text; alter table presupuestos add column if not exists fecha_evento date; alter table presupuestos add column if not exists descripcion text; alter table presupuestos add column if not exists estado text; alter table presupuestos add column if not exists total numeric; alter table presupuestos add column if not exists iva numeric default 10; alter table presupuestos add column if not exists observaciones text;
alter table catering add column if not exists cliente text; alter table catering add column if not exists fecha date; alter table catering add column if not exists hora_inicio time; alter table catering add column if not exists hora_fin time; alter table catering add column if not exists lugar text; alter table catering add column if not exists personas integer; alter table catering add column if not exists estado text; alter table catering add column if not exists responsable text; alter table catering add column if not exists observaciones text;
alter table produccion add column if not exists fecha date; alter table produccion add column if not exists cliente text; alter table produccion add column if not exists pedido text; alter table produccion add column if not exists producto text; alter table produccion add column if not exists cantidad numeric; alter table produccion add column if not exists unidad text; alter table produccion add column if not exists estado text; alter table produccion add column if not exists responsable text; alter table produccion add column if not exists notas text;
alter table dietario_anual add column if not exists fecha date; alter table dietario_anual add column if not exists producto text; alter table dietario_anual add column if not exists unidades numeric; alter table dietario_anual add column if not exists turno text; alter table dietario_anual add column if not exists responsable text; alter table dietario_anual add column if not exists festivo boolean default false; alter table dietario_anual add column if not exists notas text;
alter table menaje add column if not exists nombre text; alter table menaje add column if not exists categoria text; alter table menaje add column if not exists stock_total numeric; alter table menaje add column if not exists stock_disponible numeric; alter table menaje add column if not exists stock_reservado numeric; alter table menaje add column if not exists precio_alquiler numeric; alter table menaje add column if not exists ubicacion text; alter table menaje add column if not exists observaciones text; alter table menaje add column if not exists activo boolean default true;
alter table bebidas add column if not exists nombre text; alter table bebidas add column if not exists categoria text; alter table bebidas add column if not exists formato text; alter table bebidas add column if not exists stock numeric; alter table bebidas add column if not exists coste numeric; alter table bebidas add column if not exists precio_venta numeric; alter table bebidas add column if not exists proveedor text; alter table bebidas add column if not exists activo boolean default true;
alter table escandallos add column if not exists producto text; alter table escandallos add column if not exists coste_ingredientes numeric; alter table escandallos add column if not exists mano_obra numeric; alter table escandallos add column if not exists packaging numeric; alter table escandallos add column if not exists indirectos_pct numeric default 8; alter table escandallos add column if not exists coste_total numeric; alter table escandallos add column if not exists precio_venta numeric; alter table escandallos add column if not exists margen_pct numeric; alter table escandallos add column if not exists observaciones text;
alter table proveedores add column if not exists nombre text; alter table proveedores add column if not exists nombre_comercial text; alter table proveedores add column if not exists contacto text; alter table proveedores add column if not exists telefono text; alter table proveedores add column if not exists email text; alter table proveedores add column if not exists cif text; alter table proveedores add column if not exists condiciones_pago text; alter table proveedores add column if not exists observaciones text; alter table proveedores add column if not exists activo boolean default true;
alter table catalogo_proveedores add column if not exists proveedor text; alter table catalogo_proveedores add column if not exists producto text; alter table catalogo_proveedores add column if not exists categoria text; alter table catalogo_proveedores add column if not exists codigo_proveedor text; alter table catalogo_proveedores add column if not exists cantidad_formato numeric; alter table catalogo_proveedores add column if not exists unidad text; alter table catalogo_proveedores add column if not exists precio_sin_iva numeric; alter table catalogo_proveedores add column if not exists iva numeric default 10; alter table catalogo_proveedores add column if not exists precio_con_iva numeric; alter table catalogo_proveedores add column if not exists precio_unitario numeric; alter table catalogo_proveedores add column if not exists fecha_precio date; alter table catalogo_proveedores add column if not exists activo boolean default true;
alter table compras add column if not exists numero text; alter table compras add column if not exists fecha date; alter table compras add column if not exists proveedor text; alter table compras add column if not exists producto text; alter table compras add column if not exists cantidad numeric; alter table compras add column if not exists total numeric; alter table compras add column if not exists estado text; alter table compras add column if not exists fecha_entrega date; alter table compras add column if not exists observaciones text;
alter table visitadores_medicos add column if not exists nombre text; alter table visitadores_medicos add column if not exists laboratorio text; alter table visitadores_medicos add column if not exists telefono text; alter table visitadores_medicos add column if not exists email text; alter table visitadores_medicos add column if not exists zona text; alter table visitadores_medicos add column if not exists ultimo_contacto date; alter table visitadores_medicos add column if not exists observaciones text; alter table visitadores_medicos add column if not exists activo boolean default true;
alter table fichas_tecnicas add column if not exists producto text; alter table fichas_tecnicas add column if not exists version text; alter table fichas_tecnicas add column if not exists rendimiento text; alter table fichas_tecnicas add column if not exists elaboracion text; alter table fichas_tecnicas add column if not exists conservacion text; alter table fichas_tecnicas add column if not exists caducidad text; alter table fichas_tecnicas add column if not exists alergenos text; alter table fichas_tecnicas add column if not exists presentacion text; alter table fichas_tecnicas add column if not exists activo boolean default true;
alter table facturas add column if not exists numero text; alter table facturas add column if not exists fecha date; alter table facturas add column if not exists cliente text; alter table facturas add column if not exists concepto text; alter table facturas add column if not exists base_imponible numeric; alter table facturas add column if not exists iva numeric default 10; alter table facturas add column if not exists total numeric; alter table facturas add column if not exists estado text; alter table facturas add column if not exists fecha_cobro date; alter table facturas add column if not exists observaciones text;
