import { useEffect, useState } from "react";
import { supabase } from "../supabase.js";
import { leerRecogidaAceitePdf } from "../services/lectorAceite.js";
import { Pagina, Tabla } from "./limpieza.jsx";

const vacio = () => ({ fecha_recogida: new Date().toISOString().slice(0, 10), gestor: "Olleco Bunge IB, S.L.", numero_documento: "", numero_factura: "", cantidad_kg: "", importe: "", codigo_residuo: "20 01 25", observaciones: "" });

export default function Aceite() {
  const [form, setForm] = useState(vacio), [archivo, setArchivo] = useState(null), [registros, setRegistros] = useState([]), [mensaje, setMensaje] = useState(""), [leyendo, setLeyendo] = useState(false);
  async function cargar() { const { data, error } = await supabase.from("higiene_aceite_recogidas").select("*").order("fecha_recogida", { ascending: false }); if (error) setMensaje(`No se pudo cargar: ${error.message}`); else setRegistros(data || []); }
  useEffect(() => { cargar(); }, []);
  async function seleccionar(e) { const pdf = e.target.files?.[0]; if (!pdf) return; setArchivo(pdf); setLeyendo(true); setMensaje("Leyendo el justificante…"); try { const datos = await leerRecogidaAceitePdf(pdf); setForm((actual) => ({ ...actual, ...datos })); setMensaje("Datos extraídos. Revísalos antes de guardar."); } catch (error) { setMensaje(`No se pudo leer automáticamente: ${error.message}`); } finally { setLeyendo(false); } }
  async function guardar(e) { e.preventDefault(); if (!archivo) return setMensaje("Selecciona el PDF de la recogida."); setMensaje("Guardando…"); const ruta = `aceite/${Date.now()}-${archivo.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const subida = await supabase.storage.from("higiene-pdfs").upload(ruta, archivo, { contentType: "application/pdf" }); if (subida.error) return setMensaje(`No se pudo guardar el PDF: ${subida.error.message}`); const { error } = await supabase.from("higiene_aceite_recogidas").insert({ ...form, cantidad_kg: form.cantidad_kg === "" ? null : Number(form.cantidad_kg), importe: form.importe === "" ? null : Number(form.importe), archivo_nombre: archivo.name, archivo_ruta: ruta }); if (error) { await supabase.storage.from("higiene-pdfs").remove([ruta]); return setMensaje(`No se pudo guardar: ${error.message}`); } setForm(vacio()); setArchivo(null); setMensaje("Recogida y PDF guardados correctamente."); cargar(); }
  async function abrir(r) { const { data, error } = await supabase.storage.from("higiene-pdfs").createSignedUrl(r.archivo_ruta, 60); if (error) setMensaje(error.message); else window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  const campo = (nombre, etiqueta, tipo = "text", requerido = false) => <label>{etiqueta}{requerido && " *"}<input required={requerido} type={tipo} step={tipo === "number" ? "0.01" : undefined} value={form[nombre]} onChange={(e) => setForm({ ...form, [nombre]: e.target.value })}/></label>;
  return <Pagina icono="🛢️" titulo="Registro de aceite usado" texto="Guarda los justificantes de recogida y conserva el histórico del residuo LER 20 01 25."><h2>Nueva recogida</h2><form className="control-form" onSubmit={guardar}><label className="subida-pdf"><input type="file" accept="application/pdf,.pdf" onChange={seleccionar}/><strong>{archivo ? archivo.name : "Seleccionar PDF de la recogida"}</strong><span>{leyendo ? "Leyendo el documento…" : "Se completarán automáticamente fecha, albarán, kilos y gestor."}</span></label><div className="control-grid">{campo("fecha_recogida", "Fecha de recogida", "date", true)}{campo("gestor", "Empresa gestora", "text", true)}{campo("numero_documento", "N.º de albarán", "text", true)}{campo("numero_factura", "N.º de factura")}{campo("cantidad_kg", "Cantidad recogida (kg)", "number", true)}{campo("importe", "Importe (€)", "number")}{campo("codigo_residuo", "Código LER")}{campo("observaciones", "Observaciones")}</div><button type="submit" className="boton-control">Guardar recogida y PDF</button></form>{mensaje && <p className="mensaje-control">{mensaje}</p>}<hr className="separador-control"/><h2>Histórico de recogidas</h2><Tabla cab={["Fecha", "Gestor", "Albarán / factura", "Cantidad", "Importe", "LER", "PDF"]} datos={registros} fila={(r) => <tr key={r.id}><td>{r.fecha_recogida}</td><td>{r.gestor}</td><td><strong>{r.numero_documento}</strong><small>{r.numero_factura}</small></td><td>{r.cantidad_kg ?? "—"} kg</td><td>{r.importe == null ? "—" : `${Number(r.importe).toFixed(2)} €`}</td><td>{r.codigo_residuo}</td><td><button onClick={() => abrir(r)}>Ver PDF</button></td></tr>}/></Pagina>;
}
