import { useEffect, useState } from "react";
import { supabase } from "../supabase.js";
import { Pagina, Tabla } from "./limpieza.jsx";
import { leerFacturaAguaPdf } from "../services/lectorAgua.js";

const vacio = () => ({ proveedor: "Aigües de Barcelona", numero_factura: "", fecha_factura: new Date().toISOString().slice(0, 10), periodo_desde: "", periodo_hasta: "", consumo_m3: "", importe_total: "", observaciones: "" });
export default function Agua() {
  const [form, setForm] = useState(vacio), [archivo, setArchivo] = useState(null), [registros, setRegistros] = useState([]), [mensaje, setMensaje] = useState(""), [leyendo, setLeyendo] = useState(false);
  async function cargar() { const { data, error } = await supabase.from("higiene_facturas_agua").select("*").order("fecha_factura", { ascending: false }); if (error) setMensaje(`No se pudo cargar: ${error.message}`); else setRegistros(data || []); }
  useEffect(() => { cargar(); }, []);
  async function seleccionar(e) { const pdf = e.target.files?.[0]; if (!pdf) return; setArchivo(pdf); setLeyendo(true); setMensaje("Leyendo la factura…"); try { const datos = await leerFacturaAguaPdf(pdf); setForm((actual) => ({ ...actual, ...Object.fromEntries(Object.entries(datos).filter(([, v]) => v !== "")) })); setMensaje("Datos extraídos. Revísalos antes de guardar."); } catch (error) { setMensaje(`No se pudo leer automáticamente: ${error.message}`); } finally { setLeyendo(false); } }
  async function guardar(e) { e.preventDefault(); if (!archivo) return setMensaje("Selecciona la factura de agua en PDF."); setMensaje("Guardando…"); const ruta = `agua/${Date.now()}-${archivo.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const subida = await supabase.storage.from("higiene-pdfs").upload(ruta, archivo, { contentType: "application/pdf" }); if (subida.error) return setMensaje(`No se pudo guardar el PDF: ${subida.error.message}`); const payload = { ...form, periodo_desde: form.periodo_desde || null, periodo_hasta: form.periodo_hasta || null, consumo_m3: form.consumo_m3 === "" ? null : Number(form.consumo_m3), importe_total: form.importe_total === "" ? null : Number(form.importe_total), archivo_nombre: archivo.name, archivo_ruta: ruta }; const { error } = await supabase.from("higiene_facturas_agua").insert(payload); if (error) { await supabase.storage.from("higiene-pdfs").remove([ruta]); return setMensaje(`No se pudo guardar: ${error.message}`); } setForm(vacio()); setArchivo(null); setMensaje("Factura de agua guardada correctamente."); cargar(); }
  async function abrir(r) { const { data, error } = await supabase.storage.from("higiene-pdfs").createSignedUrl(r.archivo_ruta, 60); if (error) setMensaje(error.message); else window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  const campo = (nombre, etiqueta, tipo = "text", requerido = false) => <label>{etiqueta}{requerido && " *"}<input required={requerido} type={tipo} step={tipo === "number" ? "0.01" : undefined} value={form[nombre]} onChange={(e) => setForm({ ...form, [nombre]: e.target.value })}/></label>;
  return <Pagina icono="💧" titulo="Facturas de agua" texto="Guarda las facturas, el consumo y el importe para mantener un histórico consultable."><h2>Nueva factura</h2><form className="control-form" onSubmit={guardar}><label className="subida-pdf"><input type="file" accept="application/pdf,.pdf" onChange={seleccionar}/><strong>{archivo ? archivo.name : "Seleccionar factura de agua en PDF"}</strong><span>{leyendo ? "Leyendo la factura…" : "El sistema intentará completar proveedor, número, fechas, consumo e importe."}</span></label><div className="control-grid">{campo("proveedor", "Proveedor", "text", true)}{campo("numero_factura", "Número de factura", "text", true)}{campo("fecha_factura", "Fecha de factura", "date", true)}{campo("periodo_desde", "Periodo desde", "date")}{campo("periodo_hasta", "Periodo hasta", "date")}{campo("consumo_m3", "Consumo (m³)", "number")}{campo("importe_total", "Importe total (€)", "number")}{campo("observaciones", "Observaciones")}</div><button type="submit" className="boton-control">Guardar factura y PDF</button></form>{mensaje && <p className="mensaje-control">{mensaje}</p>}<hr className="separador-control"/><h2>Histórico de facturas</h2><Tabla cab={["Fecha", "Proveedor", "Factura", "Periodo", "Consumo", "Importe", "PDF"]} datos={registros} fila={(r) => <tr key={r.id}><td>{r.fecha_factura}</td><td>{r.proveedor}</td><td><strong>{r.numero_factura}</strong></td><td>{r.periodo_desde || "—"}<small>{r.periodo_hasta ? `a ${r.periodo_hasta}` : ""}</small></td><td>{r.consumo_m3 == null ? "—" : `${r.consumo_m3} m³`}</td><td>{r.importe_total == null ? "—" : `${Number(r.importe_total).toFixed(2)} €`}</td><td><button onClick={() => abrir(r)}>Ver PDF</button></td></tr>}/></Pagina>;
}
