import { useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase.js";

const INICIAL={nombre:"",categoria:"",producto_id:"",unidades_producidas:"1",precio_venta:"",margen_objetivo:"55",observaciones:"",activo:true};
export default function Escandallos(){
 const [escandallos,setEscandallos]=useState([]),[productos,setProductos]=useState([]),[catalogo,setCatalogo]=useState([]),[relaciones,setRelaciones]=useState([]),[lineas,setLineas]=useState([]);
 const [form,setForm]=useState(INICIAL),[editando,setEditando]=useState(null),[buscarCatalogo,setBuscarCatalogo]=useState(""),[cantidad,setCantidad]=useState(""),[seleccion,setSeleccion]=useState(""),[buscar,setBuscar]=useState(""),[error,setError]=useState(""),[mensaje,setMensaje]=useState(""),[guardando,setGuardando]=useState(false),[cargando,setCargando]=useState(true);
 useEffect(()=>{cargar();},[]);
 async function cargar(){setCargando(true);const [a,b,c,d]=await Promise.all([
  supabase.from("escandallos").select("*").order("nombre"),
  supabase.from("productos").select("id,nombre,categoria,unidad,precio_venta,activo").order("nombre"),
  supabase.from("catalogo_proveedores").select("id,proveedor_id,proveedor,producto,codigo_proveedor,cantidad_formato,unidad,precio_sin_iva,precio_unitario,fecha_precio,activo").eq("activo",true).order("producto"),
  supabase.from("producto_buenas_practicas_relaciones").select("*").eq("activo",true)
 ]);if(a.error||b.error||c.error||d.error)setError(a.error?.message||b.error?.message||c.error?.message||d.error?.message);else{setEscandallos(a.data||[]);setProductos((b.data||[]).filter(x=>x.activo!==false));setCatalogo(c.data||[]);setRelaciones(d.data||[]);}setCargando(false);}
 const opciones=useMemo(()=>{const q=buscarCatalogo.trim().toLowerCase();if(q.length<2)return [];return catalogo.filter(x=>`${x.producto} ${x.proveedor||""} ${x.codigo_proveedor||""}`.toLowerCase().includes(q)).slice(0,40);},[catalogo,buscarCatalogo]);
 useEffect(()=>{if(opciones.length===1)setSeleccion(String(opciones[0].id));else if(seleccion&&!opciones.some(x=>String(x.id)===String(seleccion)))setSeleccion("");},[opciones,seleccion]);
 function precio(x){return Number(x?.precio_unitario||x?.precio_sin_iva||0);}
 function cambiarProducto(id){const p=productos.find(x=>String(x.id)===String(id));setForm(f=>({...f,producto_id:id,nombre:!editando&&p?.nombre? p.nombre:f.nombre,categoria:!editando&&p?.categoria? p.categoria:f.categoria,precio_venta:p?String(Number(p.precio_venta||0)):""}));}
 function añadir(){setError("");let id=seleccion;if(!id&&opciones.length===1)id=String(opciones[0].id);const item=catalogo.find(x=>String(x.id)===String(id));const cant=Number(cantidad);if(!item)return setError("Selecciona uno de los productos encontrados.");if(cant<=0)return setError("Indica una cantidad mayor que cero.");setLineas(xs=>xs.some(x=>String(x.catalogo_proveedor_id)===String(item.id))?xs.map(x=>String(x.catalogo_proveedor_id)===String(item.id)?{...x,cantidad:Number(x.cantidad)+cant}:x):[...xs,{catalogo_proveedor_id:item.id,cantidad:cant,item}]);setSeleccion("");setCantidad("");setBuscarCatalogo("");setMensaje(`${item.producto} añadido.`);}
 function limpiar(){setForm(INICIAL);setLineas([]);setEditando(null);setSeleccion("");setCantidad("");setBuscarCatalogo("");}
 function editar(e){const rs=relaciones.filter(r=>String(r.escandallo_id)===String(e.id)&&r.catalogo_proveedor_id);const pid=rs[0]?.producto_id||"";const p=productos.find(x=>String(x.id)===String(pid));setForm({nombre:e.nombre||p?.nombre||"",categoria:e.categoria||p?.categoria||"",producto_id:pid,unidades_producidas:e.unidades_producidas||1,precio_venta:p?String(Number(p.precio_venta||0)):String(e.precio_venta||0),margen_objetivo:e.margen_objetivo||55,observaciones:e.observaciones||"",activo:e.activo!==false});setLineas(rs.map(r=>({catalogo_proveedor_id:r.catalogo_proveedor_id,cantidad:Number(r.cantidad_por_unidad||0)*Number(e.unidades_producidas||1),item:catalogo.find(c=>String(c.id)===String(r.catalogo_proveedor_id))})).filter(x=>x.item));setEditando(e.id);window.scrollTo({top:0,behavior:"smooth"});}
 async function guardar(ev){ev.preventDefault();setError("");setMensaje("");if(!form.producto_id)return setError("Selecciona el producto de Catering.");if(!form.nombre.trim())return setError("Indica el nombre del escandallo.");if(!lineas.length)return setError("Añade al menos un producto del catálogo de proveedores.");const u=Number(form.unidades_producidas||0);if(u<=0)return setError("Las unidades producidas deben ser mayores que cero.");const producto=productos.find(x=>String(x.id)===String(form.producto_id));const pv=Number(producto?.precio_venta||form.precio_venta||0);setGuardando(true);const datos={nombre:form.nombre.trim(),categoria:form.categoria.trim()||null,unidades_producidas:u,precio_venta:pv,margen_objetivo:Number(form.margen_objetivo||55),observaciones:form.observaciones.trim()||null,activo:form.activo,updated_at:new Date().toISOString()};let id=editando;if(editando){const {error:e}=await supabase.from("escandallos").update(datos).eq("id",editando);if(e){setGuardando(false);return setError(e.message);}const {error:er}=await supabase.from("producto_buenas_practicas_relaciones").delete().eq("escandallo_id",editando);if(er){setGuardando(false);return setError(er.message);}}else{const {data,error:e}=await supabase.from("escandallos").insert(datos).select("id").single();if(e){setGuardando(false);return setError(e.message);}id=data.id;}const rows=lineas.map((l,i)=>({producto_id:form.producto_id,catalogo_proveedor_id:l.catalogo_proveedor_id,ingrediente_id:null,escandallo_id:id,tipo_relacion:"ingrediente",cantidad_por_unidad:Number(l.cantidad)/u,unidad:l.item?.unidad||"ud",merma_pct:0,es_principal:i===0,activo:true}));const {error:er}=await supabase.from("producto_buenas_practicas_relaciones").insert(rows);if(er){setGuardando(false);return setError(er.message);}setMensaje("Escandallo guardado correctamente.");limpiar();setGuardando(false);await cargar();}
 async function eliminar(e){if(!confirm(`¿Eliminar “${e.nombre}”?`))return;await supabase.from("producto_buenas_practicas_relaciones").delete().eq("escandallo_id",e.id);await supabase.from("escandallo_ingredientes").delete().eq("escandallo_id",e.id);const {error:er}=await supabase.from("escandallos").delete().eq("id",e.id);if(er)return setError(er.message);await cargar();}
 const productoActual=productos.find(x=>String(x.id)===String(form.producto_id));const venta=Number(productoActual?.precio_venta||form.precio_venta||0);const coste=useMemo(()=>lineas.reduce((t,l)=>t+Number(l.cantidad||0)*precio(l.item),0),[lineas]);const unidad=Number(form.unidades_producidas||0)>0?coste/Number(form.unidades_producidas):0;const margen=venta>0?((venta-unidad)/venta)*100:0;const recomendado=Number(form.margen_objetivo||55)<100?unidad/(1-Number(form.margen_objetivo||55)/100):0;
 function calc(e){const rs=relaciones.filter(r=>String(r.escandallo_id)===String(e.id)&&r.catalogo_proveedor_id);const cu=rs.reduce((t,r)=>t+Number(r.cantidad_por_unidad||0)*precio(catalogo.find(c=>String(c.id)===String(r.catalogo_proveedor_id))),0);const p=productos.find(x=>String(x.id)===String(rs[0]?.producto_id));const pv=Number(p?.precio_venta||e.precio_venta||0);return{n:rs.length,cu,pv,m:pv>0?((pv-cu)/pv)*100:0,pid:rs[0]?.producto_id};}
 const filtrados=escandallos.filter(e=>!buscar.trim()||`${e.nombre} ${e.categoria||""}`.toLowerCase().includes(buscar.toLowerCase()));
 return <section className="panel"><div className="titulo-seccion"><div><p className="etiqueta">Producción, costes y compras</p><h2>Escandallos</h2><p>Precio de venta desde Productos · Coste desde Catálogo de Proveedores.</p></div></div><form onSubmit={guardar} style={box}><h3>{editando?"Editar escandallo":"Nuevo escandallo"}</h3><div style={grid}><label>Producto de Catering *<select style={campo} value={form.producto_id} onChange={e=>cambiarProducto(e.target.value)}><option value="">Selecciona producto</option>{productos.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><label>Nombre escandallo *<input style={campo} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Categoría<input style={campo} value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}/></label><label>Unidades producidas<input type="number" min=".01" step=".01" style={campo} value={form.unidades_producidas} onChange={e=>setForm({...form,unidades_producidas:e.target.value})}/></label><label>Precio venta / unidad (Productos)<input readOnly style={{...campo,background:"#eee",color:"#222",fontWeight:700}} value={venta?venta.toFixed(2):"0.00"}/></label><label>Margen objetivo %<input type="number" min="0" max="99.99" step=".01" style={campo} value={form.margen_objetivo} onChange={e=>setForm({...form,margen_objetivo:e.target.value})}/></label></div>
 <div style={{...box,marginTop:18,marginBottom:0}}><h3>Productos del Catálogo de Proveedores</h3><input style={campo} placeholder="Buscar: Gran Cristallino, jamón, tomate..." value={buscarCatalogo} onChange={e=>{setBuscarCatalogo(e.target.value);setSeleccion("");setError("");}}/>{opciones.length>0&&<div style={{marginTop:8,display:"grid",gap:6}}>{opciones.map(x=><button key={x.id} type="button" onClick={()=>setSeleccion(String(x.id))} style={{textAlign:"left",padding:12,borderRadius:10,border:String(seleccion)===String(x.id)?"3px solid #6b007b":"1px solid #aaa",background:String(seleccion)===String(x.id)?"#f1e5f5":"white",color:"#222",cursor:"pointer"}}><strong>{x.producto}</strong> · {x.proveedor||"Proveedor"} · {euros(precio(x))}/{x.unidad||"ud"}{String(seleccion)===String(x.id)?" ✓ SELECCIONADO":""}</button>)}</div>}<div style={linea}><input type="number" min=".0001" step=".0001" style={campo} placeholder="Cantidad usada" value={cantidad} onChange={e=>setCantidad(e.target.value)}/><button type="button" onClick={añadir}>Añadir producto</button></div>{lineas.map((l,i)=><div style={fila} key={l.catalogo_proveedor_id}><div><strong>{l.item?.producto}</strong><small style={{display:"block",opacity:.7}}>{l.item?.proveedor||"Proveedor"}</small></div><span>{euros(precio(l.item))}/{l.item?.unidad||"ud"}</span><input type="number" min=".0001" step=".0001" style={{...campo,margin:0}} value={l.cantidad} onChange={e=>setLineas(xs=>xs.map((x,j)=>j===i?{...x,cantidad:e.target.value}:x))}/><strong>{euros(Number(l.cantidad)*precio(l.item))}</strong><button type="button" className="boton-cancelar" onClick={()=>setLineas(xs=>xs.filter((_,j)=>j!==i))}>Quitar</button></div>)}</div>
 <div style={cards}><Card t="Coste receta" v={euros(coste)}/><Card t="Coste unidad" v={euros(unidad)}/><Card t="Precio venta" v={euros(venta)}/><Card t="Margen real" v={`${num(margen)} %`}/><Card t="Precio recomendado" v={euros(recomendado)}/></div>{margen>0&&margen<55&&<p style={{color:"#b00020",fontWeight:700}}>⚠ Margen inferior al 55 %</p>}<label style={{display:"block",marginTop:16}}>Observaciones<textarea rows="3" style={{...campo,padding:10}} value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label>{error&&<p style={{color:"#b00020"}}>Error: {error}</p>}{mensaje&&<p style={{color:"#16813d"}}>{mensaje}</p>}<div style={{display:"flex",gap:10,marginTop:16}}><button disabled={guardando}>{guardando?"Guardando...":editando?"Guardar cambios":"Crear escandallo"}</button>{editando&&<button type="button" className="boton-cancelar" onClick={limpiar}>Cancelar</button>}</div></form><input style={{...campo,marginBottom:16}} placeholder="Buscar escandallo..." value={buscar} onChange={e=>setBuscar(e.target.value)}/>{cargando?<p>Cargando...</p>:<div style={{overflowX:"auto"}}><table style={tabla}><thead><tr><th>Producto Catering</th><th>Escandallo</th><th>Productos proveedor</th><th>Coste unidad</th><th>Venta</th><th>Margen</th><th>Acciones</th></tr></thead><tbody>{filtrados.map(e=>{const c=calc(e),p=productos.find(x=>String(x.id)===String(c.pid));return <tr key={e.id}><td><strong>{p?.nombre||"Sin vincular"}</strong></td><td>{e.nombre}</td><td>{c.n}</td><td>{euros(c.cu)}</td><td>{euros(c.pv)}</td><td>{num(c.m)} %{c.m<55&&<div style={{color:"#b00020"}}>Margen bajo</div>}</td><td><button type="button" onClick={()=>editar(e)}>Editar</button> <button type="button" className="boton-cancelar" onClick={()=>eliminar(e)}>Eliminar</button></td></tr>})}</tbody></table></div>}</section>;
}
function Card({t,v}){return <div style={{padding:14,border:"1px solid #ddd",borderRadius:12}}><span>{t}</span><br/><strong style={{fontSize:22}}>{v}</strong></div>}function euros(v){return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(Number(v||0))}function num(v){return new Intl.NumberFormat("es-ES",{maximumFractionDigits:2}).format(Number(v||0))}
const campo={display:"block",width:"100%",boxSizing:"border-box",marginTop:8,minHeight:46,padding:"0 12px",borderRadius:10,border:"1px solid #4b4453",background:"#151319",color:"white",fontSize:16};const box={marginBottom:26,padding:20,border:"1px solid #ccc",borderRadius:16};const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14};const linea={display:"grid",gridTemplateColumns:"minmax(180px,1fr) auto",gap:10,alignItems:"end",marginTop:10};const fila={display:"grid",gridTemplateColumns:"minmax(220px,2fr) 180px 130px 120px auto",gap:10,alignItems:"center",padding:"10px 0",borderBottom:"1px solid #ddd"};const cards={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginTop:18};const tabla={width:"100%",borderCollapse:"collapse",minWidth:900};