import { useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase.js";
import { leerPdfTemperaturas } from "../services/lectorTemperaturas.js";

const vacio = { numero_serie: "", nombre_ubicacion: "", tipo_equipo: "Congelador", limite_minimo: -30, limite_maximo: -18, fecha_inicio: null, fecha_fin: null, temperatura_minima: null, temperatura_maxima: null, temperatura_media: null, numero_registros: null, intervalo: "", archivo_nombre: "" };
const fecha = (v) => v ? new Intl.DateTimeFormat("es-ES", { dateStyle: "short", timeStyle: "short" }).format(new Date(v)) : "—";
const grados = (v) => v === null || v === undefined ? "—" : `${Number(v).toFixed(1)} °C`;

export default function Temperaturas() {
  const [registros, setRegistros] = useState([]); const [form, setForm] = useState(vacio); const [archivo, setArchivo] = useState(null);
  const [leyendo, setLeyendo] = useState(false); const [progreso, setProgreso] = useState(0); const [mensaje, setMensaje] = useState(""); const [busqueda, setBusqueda] = useState("");
  async function cargar() { const { data, error } = await supabase.from("higiene_temperaturas").select("*").order("fecha_inicio", { ascending: false }); if (!error) setRegistros(data || []); }
  useEffect(() => { cargar(); }, []);
  async function seleccionar(e) { const f = e.target.files?.[0]; if (!f) return; setArchivo(f); setLeyendo(true); setMensaje(""); try { const datos = await leerPdfTemperaturas(f, setProgreso); const anterior = registros.find((r) => r.numero_serie === datos.numero_serie); setForm({ ...vacio, ...datos, nombre_ubicacion: datos.nombre_ubicacion || anterior?.nombre_ubicacion || "" }); } catch (err) { setMensaje(err.message); } finally { setLeyendo(false); } }
  async function guardar(e) { e.preventDefault(); if (!archivo || !form.numero_serie || !form.nombre_ubicacion) return setMensaje("Falta el PDF, el número de serie o el nombre del equipo."); setMensaje("Guardando…"); const ruta = `${form.numero_serie}/${Date.now()}-${archivo.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const subida = await supabase.storage.from("higiene-pdfs").upload(ruta, archivo, { contentType: "application/pdf" }); if (subida.error) return setMensaje(`No se pudo guardar el PDF: ${subida.error.message}`); const { error } = await supabase.from("higiene_temperaturas").insert({ ...form, archivo_ruta: ruta }); if (error) return setMensaje(error.message); setMensaje("PDF leído y registro guardado correctamente."); setForm(vacio); setArchivo(null); setProgreso(0); await cargar(); }
  async function abrir(registro) { const { data, error } = await supabase.storage.from("higiene-pdfs").createSignedUrl(registro.archivo_ruta, 60); if (error) return setMensaje(error.message); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  async function eliminar(registro) { if (!window.confirm(`¿Eliminar el registro de ${registro.nombre_ubicacion}?`)) return; await supabase.storage.from("higiene-pdfs").remove([registro.archivo_ruta]); const { error } = await supabase.from("higiene_temperaturas").delete().eq("id", registro.id); if (error) setMensaje(error.message); else cargar(); }
  const filtrados = useMemo(() => registros.filter((r) => `${r.nombre_ubicacion} ${r.numero_serie}`.toLowerCase().includes(busqueda.toLowerCase())), [registros, busqueda]);
  const fuera = form.temperatura_maxima !== null && (Number(form.temperatura_maxima) > Number(form.limite_maximo) || Number(form.temperatura_minima) < Number(form.limite_minimo));
  return <div className="pagina-control-higiene"><header className="control-cabecera"><div><span>🌡️ AUTOCONTROL</span><h1>Temperaturas</h1><p>Sube el PDF del registrador, identifica dónde estaba colocado y conserva el histórico.</p></div></header>
    <section className="control-panel"><h2>Subir un registro</h2><form onSubmit={guardar} className="control-form"><label className="subida-pdf"><input type="file" accept="application/pdf,.pdf" onChange={seleccionar}/><strong>{archivo ? archivo.name : "Seleccionar PDF del termómetro"}</strong><span>{leyendo ? `Leyendo… ${progreso}%` : "El sistema extraerá automáticamente fechas, temperaturas y número de serie"}</span></label>{form.numero_serie && <><div className="control-grid"><label>Número de serie<input value={form.numero_serie} readOnly/></label><label>Nombre / ubicación *<input value={form.nombre_ubicacion} onChange={(e)=>setForm({...form,nombre_ubicacion:e.target.value})} placeholder="Ej. Congelador de pan" required/></label><label>Tipo de equipo<select value={form.tipo_equipo} onChange={(e)=>setForm({...form,tipo_equipo:e.target.value})}><option>Congelador</option><option>Nevera</option><option>Cámara</option><option>Elaboración</option><option>Otro</option></select></label><label>Límite mínimo °C<input type="number" step="0.1" value={form.limite_minimo} onChange={(e)=>setForm({...form,limite_minimo:e.target.value})}/></label><label>Límite máximo °C<input type="number" step="0.1" value={form.limite_maximo} onChange={(e)=>setForm({...form,limite_maximo:e.target.value})}/></label></div><div className="resumen-temperatura"><div><small>Inicio</small><strong>{fecha(form.fecha_inicio)}</strong></div><div><small>Mínima</small><strong>{grados(form.temperatura_minima)}</strong></div><div><small>Media</small><strong>{grados(form.temperatura_media)}</strong></div><div><small>Máxima</small><strong>{grados(form.temperatura_maxima)}</strong></div><div><small>Lecturas</small><strong>{form.numero_registros || "—"}</strong></div></div>{fuera && <div className="alerta-control">⚠️ El informe contiene temperaturas fuera de los límites indicados. Registra una incidencia si corresponde.</div>}<button className="boton-control" type="submit">Guardar registro y PDF</button></>}</form>{mensaje && <p className="mensaje-control">{mensaje}</p>}</section>
    <section className="control-panel"><div className="control-titulo-fila"><h2>Histórico</h2><input value={busqueda} onChange={(e)=>setBusqueda(e.target.value)} placeholder="Buscar equipo o número de serie"/></div><div className="tabla-control-wrap"><table className="tabla-control"><thead><tr><th>Equipo / ubicación</th><th>Serie</th><th>Periodo</th><th>Mín.</th><th>Media</th><th>Máx.</th><th>PDF</th></tr></thead><tbody>{filtrados.map((r)=><tr key={r.id}><td><strong>{r.nombre_ubicacion}</strong><small>{r.tipo_equipo}</small></td><td>{r.numero_serie}</td><td>{fecha(r.fecha_inicio)}<small>hasta {fecha(r.fecha_fin)}</small></td><td>{grados(r.temperatura_minima)}</td><td>{grados(r.temperatura_media)}</td><td>{grados(r.temperatura_maxima)}</td><td><button onClick={()=>abrir(r)}>Ver</button><button className="peligro" onClick={()=>eliminar(r)}>Eliminar</button></td></tr>)}{!filtrados.length&&<tr><td colSpan="7" className="tabla-vacia">Todavía no hay registros.</td></tr>}</tbody></table></div></section></div>;
}
