import { supabase } from "./supabase.js";

const MESES = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
let cargando = false;
let observer = null;

function estaEnDashboard(){return location.hash==="#/"||location.hash.startsWith("#/dashboard");}
function normalizar(v){return String(v||"").trim().toLowerCase();}
function euros(v){return Number(v||0).toLocaleString("es-ES",{style:"currency",currency:"EUR",minimumFractionDigits:2});}
function fechaBonita(v){if(!v)return"—";const[y,m,d]=String(v).slice(0,10).split("-");return y&&m&&d?`${d}/${m}/${y}`:v;}
function escapar(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function esCatering(p){return !["visitador médico","visitador medico","tienda"].includes(normalizar(p.tipo_documento));}
function estadoControl(p){if(p.facturado_externamente||p.fecha_facturacion||normalizar(p.estado).includes("factur"))return"Facturado";if(normalizar(p.estado)==="cancelado")return"Cancelado";if(normalizar(p.estado)==="aceptado")return"Aceptado · pendiente de facturar";if(normalizar(p.estado)==="enviado")return"Enviado";if(normalizar(p.estado)==="borrador")return"Borrador";return p.estado||"Sin estado";}
function claseEstado(e){e=normalizar(e);if(e.startsWith("facturado"))return"facturado";if(e.startsWith("cancelado"))return"cancelado";if(e.includes("pendiente de facturar"))return"pendiente";if(e==="enviado")return"enviado";return"borrador";}

function crearPanel(){
 const dashboard=document.querySelector(".dashboard-direccion");
 if(!dashboard||document.getElementById("estadisticas-catering-dashboard"))return null;
 const panel=document.createElement("section");panel.id="estadisticas-catering-dashboard";panel.className="dashboard-estadisticas-catering";
 panel.innerHTML=`<style>
 .dashboard-hoy{display:none!important}
 .dashboard-estadisticas-catering{margin-top:28px;padding:24px;border:1px solid #ddd2e2;border-radius:20px;background:#fff}.dashboard-estadisticas-cabecera{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;flex-wrap:wrap}.dashboard-estadisticas-cabecera h2{margin:0}.dashboard-estadisticas-cabecera p{margin:6px 0 0;color:#766d7a}.dashboard-estadisticas-selectores{display:flex;gap:10px;flex-wrap:wrap}.dashboard-estadisticas-selector{display:flex;align-items:center;gap:8px;font-weight:800;color:#5c257c}.dashboard-estadisticas-selector select{min-height:40px;padding:0 12px;border:1px solid #d8cadd;border-radius:10px;background:#fff;font:inherit}.dashboard-estadisticas-resumen{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;margin-top:20px}.dashboard-estadisticas-dato{padding:16px;border-radius:14px;background:#f7f2f9;border:1px solid #eee4f1;text-align:left}.dashboard-estadisticas-dato span{display:block;color:#765d7f;font-size:11px;font-weight:900;text-transform:uppercase;line-height:1.3}.dashboard-estadisticas-dato strong{display:block;margin-top:6px;color:#5c257c;font-size:25px}.dashboard-estadisticas-error{margin-top:16px;padding:12px;border-radius:10px;background:#fde7ec;color:#a42f46}
 .dashboard-listado-mensual{margin-top:30px;padding:24px;border:2px solid #d7c5df;border-radius:20px;background:#fff}.dashboard-listado-cabecera{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap;margin-bottom:16px}.dashboard-listado-cabecera h2{margin:0}.dashboard-listado-cabecera p{margin:5px 0 0;color:#766d7a}.dashboard-control-filtros{display:flex;gap:8px;flex-wrap:wrap}.dashboard-control-filtros button{border:1px solid #d8cadd;background:#fff;color:#5c257c;border-radius:999px;padding:8px 12px;font-weight:800;cursor:pointer}.dashboard-control-filtros button.activo{background:#5c257c;color:#fff;border-color:#5c257c}.dashboard-control-tabla-wrap{overflow:auto;border:1px solid #eee7f0;border-radius:14px}.dashboard-control-tabla{width:100%;border-collapse:collapse;min-width:900px}.dashboard-control-tabla th{padding:11px 12px;text-align:left;background:#f7f2f9;color:#5c257c;font-size:12px;text-transform:uppercase}.dashboard-control-tabla td{padding:12px;border-top:1px solid #eee7f0;vertical-align:middle}.dashboard-control-tabla tr:hover td{background:#fcfafc}.dashboard-estado{display:inline-flex;padding:6px 9px;border-radius:999px;font-size:12px;font-weight:900;white-space:nowrap}.dashboard-estado.facturado{background:#e6f5ea;color:#26733c}.dashboard-estado.cancelado{background:#fde7ec;color:#a42f46}.dashboard-estado.pendiente{background:#fff1c9;color:#805b00}.dashboard-estado.enviado{background:#e8f1ff;color:#285a9d}.dashboard-estado.borrador{background:#efedf0;color:#655d68}.dashboard-abrir{display:inline-flex;padding:7px 10px;border-radius:9px;background:#5c257c;color:#fff!important;text-decoration:none;font-weight:800;white-space:nowrap}.dashboard-sin-datos{padding:22px;text-align:center;color:#766d7a}
 @media(max-width:1100px){.dashboard-estadisticas-resumen{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.dashboard-estadisticas-resumen{grid-template-columns:repeat(2,minmax(0,1fr))}.dashboard-estadisticas-catering,.dashboard-listado-mensual{padding:16px}}
 </style><div class="dashboard-estadisticas-cabecera"><div><p class="dashboard-etiqueta">CONTROL COMERCIAL</p><h2>Resumen mensual de Catering</h2><p>Presupuestos, pendientes y facturación del mes completo.</p></div><div class="dashboard-estadisticas-selectores"><label class="dashboard-estadisticas-selector">Mes <select data-estadisticas-mes></select></label><label class="dashboard-estadisticas-selector">Año <select data-estadisticas-anio></select></label></div></div><div data-estadisticas-contenido><p style="margin-top:20px">Cargando resumen mensual...</p></div>`;
 const resumenActual=dashboard.querySelector(".dashboard-resumen");if(resumenActual)resumenActual.insertAdjacentElement("afterend",panel);else dashboard.appendChild(panel);
 const listado=document.createElement("section");listado.id="listado-mensual-caterings";listado.className="dashboard-listado-mensual";listado.innerHTML=`<div data-listado-mensual><p>Cargando caterings del mes...</p></div>`;dashboard.appendChild(listado);
 const sa=panel.querySelector("[data-estadisticas-anio]"),sm=panel.querySelector("[data-estadisticas-mes]"),ahora=new Date(),actual=ahora.getFullYear();MESES.forEach((n,i)=>{const o=document.createElement("option");o.value=String(i+1);o.textContent=n;sm.appendChild(o)});sm.value=String(ahora.getMonth()+1);for(let a=actual;a>=2024;a--){const o=document.createElement("option");o.value=String(a);o.textContent=String(a);sa.appendChild(o)}sa.value=String(actual);const recargar=()=>cargarEstadisticas(Number(sa.value),Number(sm.value),panel,listado);sa.addEventListener("change",recargar);sm.addEventListener("change",recargar);recargar();return panel;
}

async function cargarEstadisticas(anio,mes,panel,listado){
 if(cargando||!panel?.isConnected)return;cargando=true;const contenido=panel.querySelector("[data-estadisticas-contenido]"),listaCont=listado.querySelector("[data-listado-mensual]");contenido.innerHTML=`<p style="margin-top:20px">Cargando ${MESES[mes-1]}...</p>`;listaCont.innerHTML=`<p>Cargando caterings de ${MESES[mes-1]}...</p>`;
 try{const mm=String(mes).padStart(2,"0"),ultimo=new Date(anio,mes,0).getDate(),inicio=`${anio}-${mm}-01`,fin=`${anio}-${mm}-${String(ultimo).padStart(2,"0")}`;
 const[pr,fr]=await Promise.all([supabase.from("presupuestos").select("id,numero,fecha,estado,tipo_documento,subtotal,iva_total,total,facturado_externamente,fecha_facturacion,cliente_id,clientes(id,nombre,empresa)").gte("fecha",inicio).lte("fecha",fin).order("fecha",{ascending:true}),supabase.from("facturas").select("id,numero,presupuesto_id,fecha_factura,total,estado,nombre_cliente").gte("fecha_factura",inicio).lte("fecha_factura",fin)]);if(pr.error)throw pr.error;if(fr.error)throw fr.error;
 const presupuestos=(pr.data||[]).filter(esCatering),facturas=(fr.data||[]).filter(f=>normalizar(f.estado)!=="anulada"),fp=new Map(facturas.filter(f=>f.presupuesto_id).map(f=>[String(f.presupuesto_id),f]));const filas=presupuestos.map(p=>{const factura=fp.get(String(p.id))||null;return{...p,factura,estadoControl:factura?"Facturado":estadoControl(p)}});const facturados=filas.filter(p=>p.estadoControl==="Facturado"),pendientes=filas.filter(p=>p.estadoControl==="Aceptado · pendiente de facturar"),cancelados=filas.filter(p=>p.estadoControl==="Cancelado"),aceptados=filas.filter(p=>["Facturado","Aceptado · pendiente de facturar"].includes(p.estadoControl)),dinero=facturas.reduce((s,f)=>s+Number(f.total||0),0);
 contenido.innerHTML=`<div class="dashboard-estadisticas-resumen"><div class="dashboard-estadisticas-dato"><span>Caterings presupuestados</span><strong>${filas.length}</strong></div><div class="dashboard-estadisticas-dato"><span>Aceptados</span><strong>${aceptados.length}</strong></div><div class="dashboard-estadisticas-dato"><span>Pendientes de facturar</span><strong>${pendientes.length}</strong></div><div class="dashboard-estadisticas-dato"><span>Caterings facturados</span><strong>${facturados.length}</strong></div><div class="dashboard-estadisticas-dato"><span>Cancelados</span><strong>${cancelados.length}</strong></div><div class="dashboard-estadisticas-dato"><span>Dinero facturado</span><strong>${euros(dinero)}</strong></div></div>`;
 listaCont.innerHTML=`<div class="dashboard-listado-cabecera"><div><p class="dashboard-etiqueta">MES COMPLETO</p><h2>Todos los caterings de ${MESES[mes-1]} ${anio}</h2><p data-contador>${filas.length} caterings del mes, ordenados por fecha.</p></div><div class="dashboard-control-filtros"><button class="activo" data-ft="todos">Todos</button><button data-ft="pendientes">Pendientes de facturar</button><button data-ft="facturados">Facturados</button><button data-ft="cancelados">Cancelados</button></div></div><div class="dashboard-control-tabla-wrap"><table class="dashboard-control-tabla"><thead><tr><th>Fecha catering</th><th>Nº presupuesto</th><th>Cliente</th><th>Importe</th><th>Estado</th><th>Nº factura</th><th></th></tr></thead><tbody data-tbody></tbody></table></div>`;
 const tbody=listaCont.querySelector("[data-tbody]"),contador=listaCont.querySelector("[data-contador]");function coincide(p,f){if(f==="todos")return true;if(f==="pendientes")return p.estadoControl==="Aceptado · pendiente de facturar";if(f==="facturados")return p.estadoControl==="Facturado";if(f==="cancelados")return p.estadoControl==="Cancelado";return true}function pintar(f="todos"){const l=filas.filter(p=>coincide(p,f));contador.textContent=`${l.length} catering${l.length===1?"":"s"} de ${MESES[mes-1]} ${anio}.`;tbody.innerHTML=l.length?l.map(p=>{const cliente=p.clientes?.empresa||p.clientes?.nombre||p.factura?.nombre_cliente||"Sin cliente";return `<tr><td><strong>${fechaBonita(p.fecha)}</strong></td><td>${escapar(p.numero||"—")}</td><td>${escapar(cliente)}</td><td><strong>${euros(Number(p.total||p.subtotal||0))}</strong></td><td><span class="dashboard-estado ${claseEstado(p.estadoControl)}">${escapar(p.estadoControl)}</span></td><td>${escapar(p.factura?.numero||(p.estadoControl==="Facturado"?"Facturado":"—"))}</td><td><a class="dashboard-abrir" href="#/presupuestos">Abrir</a></td></tr>`}).join(""):`<tr><td colspan="7" class="dashboard-sin-datos">No hay caterings con este estado en el mes seleccionado.</td></tr>`}listaCont.querySelectorAll("[data-ft]").forEach(b=>b.addEventListener("click",()=>{listaCont.querySelectorAll("[data-ft]").forEach(x=>x.classList.toggle("activo",x===b));pintar(b.dataset.ft)}));pintar();
 }catch(error){const msg=escapar(error?.message||error);contenido.innerHTML=`<div class="dashboard-estadisticas-error">No se ha podido cargar el resumen: ${msg}</div>`;listaCont.innerHTML=`<div class="dashboard-estadisticas-error">No se ha podido cargar el listado mensual: ${msg}</div>`}finally{cargando=false}
}
function sincronizar(){if(!estaEnDashboard())return;crearPanel()}function iniciar(){window.addEventListener("hashchange",()=>setTimeout(sincronizar,80));observer=new MutationObserver(()=>sincronizar());observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(sincronizar,100)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",iniciar,{once:true});else iniciar();
