import { supabase } from "./supabase.js";
let procesando=false,observer=null;
const enPresupuestos=()=>String(location.hash||"").startsWith("#/presupuestos");
function fechaES(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)}
function etiqueta(f){const s=document.createElement("span");s.className="control-facturado-etiqueta";s.textContent=`✓ FACTURADO — ${fechaES(f)}`;return s}
async function preparar(p,b){if(!p?.id||procesando)return;procesando=true;b.disabled=true;b.textContent="Preparando...";try{const[a,l]=await Promise.all([supabase.from("presupuestos").select("*, clientes(*)").eq("id",p.id).single(),supabase.from("presupuesto_lineas").select("*").eq("presupuesto_id",p.id).order("created_at",{ascending:true})]);if(a.error)throw a.error;if(l.error)throw l.error;const pr=a.data,c=pr.clientes||{},lineas=(l.data||[]).filter(x=>String(x.descripcion||"").trim()||Number(x.precio_unitario||0)).map((x,i)=>({orden:i+1,descripcion:String(x.descripcion||"Concepto").trim(),cantidad:Number(x.cantidad||0),precio_unitario:Number(x.precio_unitario||0),iva:Number(x.iva??10)}));if(!lineas.length)throw new Error("El presupuesto no tiene líneas.");let base=0,iva=0;lineas.forEach(x=>{const s=x.cantidad*x.precio_unitario;base+=s;iva+=s*x.iva/100});base=Number(base.toFixed(2));iva=Number(iva.toFixed(2));const total=Number((base+iva).toFixed(2)),ref=pr.numero||"",nombre=c.empresa||c.razon_social||c.nombre||pr.visitador_nombre||"Cliente";const ex=await supabase.from("facturas").select("id").eq("numero_pedido",ref).limit(1);if(ex.error)throw ex.error;const payload={fecha_factura:new Date().toISOString().slice(0,10),cliente_id:pr.cliente_id||null,numero_pedido:ref||null,nombre_cliente:nombre,cif:c.nif_cif||c.cif||c.nif||null,direccion:c.direccion||pr.direccion_entrega||null,codigo_postal:c.codigo_postal||c.cp||null,poblacion:c.poblacion||c.localidad||null,provincia:c.provincia||null,email:c.email||null,telefono:c.telefono||pr.telefono_contacto||null,observaciones:`Presupuesto ${ref} preparado desde Presupuestos.`,estado:"pendiente",forma_pago:"transferencia",iva_incluido:false,lineas,base_imponible:base,subtotal:base,iva,total_iva:iva,importe:total,total,manual:true,updated_at:new Date().toISOString()};let rid=ex.data?.[0]?.id;if(rid){const q=await supabase.from("facturas").update(payload).eq("id",rid);if(q.error)throw q.error}else{const q=await supabase.from("facturas").insert({...payload,numero:null}).select("id").single();if(q.error)throw q.error;rid=q.data.id}sessionStorage.setItem("cusachs_presupuesto_pendiente_facturar",JSON.stringify({presupuestoId:p.id,registroId:rid,numero:ref}));location.hash="#/facturacion"}catch(e){b.disabled=false;b.textContent="🧾 Datos para factura";alert(`No se han podido preparar los datos: ${e?.message||e}`)}finally{procesando=false}}
async function sincronizar(){if(!enPresupuestos())return;const fs=[...document.querySelectorAll("table tbody tr")];if(!fs.length)return;const ns=fs.map(f=>f.querySelector("td")?.textContent?.trim()).filter(Boolean);const q=await supabase.from("presupuestos").select("id,numero,facturado_externamente,updated_at").in("numero",ns);if(q.error)return;const m=new Map((q.data||[]).map(p=>[String(p.numero||"").trim(),p]));fs.forEach(f=>{if(f.querySelector(".control-facturado"))return;const p=m.get(f.querySelector("td")?.textContent?.trim()),a=f.querySelector("td:last-child");if(!p||!a)return;const c=document.createElement("span");c.className="control-facturado";if(p.facturado_externamente)c.appendChild(etiqueta(p.updated_at));else{const b=document.createElement("button");b.type="button";b.className="control-facturado-boton";b.textContent="🧾 Datos para factura";b.onclick=e=>{e.preventDefault();e.stopPropagation();preparar(p,b)};c.appendChild(b)}a.appendChild(c)})}
function iniciar(){const s=document.createElement("style");s.textContent=`.control-facturado{display:inline-flex;margin-left:6px}.control-facturado-boton,.control-facturado-etiqueta{display:inline-flex;align-items:center;min-height:34px;padding:7px 11px;border-radius:9px;font-size:12px;font-weight:900;white-space:nowrap}.control-facturado-boton{border:1px solid #237a47;background:#237a47;color:#fff;cursor:pointer}.control-facturado-etiqueta{background:#dff5e7;color:#176b3a;border:1px solid #b9e3c8}`;document.head.appendChild(s);window.addEventListener("hashchange",()=>setTimeout(sincronizar,120));observer=new MutationObserver(()=>{if(enPresupuestos())setTimeout(sincronizar,30)});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(sincronizar,150)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",iniciar,{once:true});else iniciar();
